<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGzKafc2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGzKafc2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGzKafc2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGzKafc2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGzKafc2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GzKafc2',
    'container.build_id' => '677b2e9a',
    'container.build_time' => 1645132498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGzKafc2');
