<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFUQg2Sx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFUQg2Sx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFUQg2Sx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFUQg2Sx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFUQg2Sx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FUQg2Sx',
    'container.build_id' => 'e9b83abb',
    'container.build_time' => 1645211479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFUQg2Sx');
